version: '3.8'
services:
  mysqldb:
    image: library/mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=data
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data_container:/var/lib/mysql
    networks:
      - dj-website-backend-network

volumes:
  mysql_data_container:

networks:
  dj-website-backend-network:
