insert into translated_value (language, key, value)
values ('nl', '7 Habits of highly effective people', 'De zeven eigenschappen van effectief leiderschap'),
       ('fr', '7 Habits of highly effective people', 'Les 7 habitudes de ceux qui réalisent tout ce qu''ils entreprennent'),
       ('nl', 'The Passionate Programmer: Creating a Remarkable Career in Software Development', 'The Passionate Programmer: Het creëren van een opmerkelijke carrière in software-ontwikkeling'),
       ('fr', 'The Passionate Programmer: Creating a Remarkable Career in Software Development', 'The Passionate Programmer : Créer une carrière remarquable dans le développement de logiciels'),
       ('nl', 'Oracle Certified Associate Java SE 8 Programmer I Study Guide', 'Oracle Certified Associate Java SE 8 Programmer I Studiegids'),
       ('fr', 'Oracle Certified Associate Java SE 8 Programmer I Study Guide', 'Oracle Certified Associate Java SE 8 Programmer I Guide d''étude'),
       ('nl', 'Ng-book: the complete book on Angular', 'Ng-book: het complete boek over Angular'),
       ('fr', 'Ng-book: the complete book on Angular', 'Ng-book: le livre complet sur Angular'),
       ('nl', 'Oracle Certified Professional Java SE 8 Programmer II Study Guide', 'Oracle Certified Professional Java SE 8 Programmer II Studiegids'),
       ('fr', 'Oracle Certified Professional Java SE 8 Programmer II Study Guide', 'Oracle Certified Professional Java SE 8 Programmer II Guide d''étude'),
       ('nl', 'The Clean Coder: A code of Conduct for Professional Programmers', 'The Clean Coder: Een gedragscode voor Professionele Programmeurs'),
       ('fr', 'The Clean Coder: A code of Conduct for Professional Programmers', 'The Clean Coder: Un code de conduite pour les Programmeurs Professionnels'),
       ('nl', 'Effective Java: A Programming Language Guide', 'Effective Java: Een programmeertaalgids'),
       ('fr', 'Effective Java: A Programming Language Guide', 'Effective Java: Guide du langage de programmatione'),
       ('nl', 'Clean Code: A Handbook of Agile Software Craftsmanship', 'Clean Code: Een Handboek van Agile Software Vakmanschap'),
       ('fr', 'Clean Code: A Handbook of Agile Software Craftsmanship', 'Clean Code: Un manuel d''Agile Software Craftsmanship'),
       ('nl', 'Head First Design Patterns: A Brain-Friendly Guide', 'Head First Design Patterns: Een hersenvriendelijke gids'),
       ('fr', 'Head First Design Patterns: A Brain-Friendly Guide', 'Head First Design Patterns: Un guide convivial pour le cerveau'),
       ('nl', 'Succeeding with Agile: Software Development Using Scrum', 'Succeeding with Agile: Softwareontwikkeling met behulp van Scrum'),
       ('fr', 'Succeeding with Agile: Software Development Using Scrum', 'Succeeding with Agile: Développement de logiciels à l''aide de Scrum'),
       ('nl', 'How to win friends and influence people', 'Hoe je vrienden maakt en mensen beïnvloedt'),
       ('fr', 'How to win friends and influence people', 'Comment se faire des amis et influencer les autres'),
       ('nl', 'Unfu*k Yourself: Get Out of Your Head and Into Your Life', 'Unfu*k Yourself: Stap uit je hoofd en in je leven'),
       ('fr', 'Unfu*k Yourself: Get Out of Your Head and Into Your Life', 'Unfu*k Yourself: Sortez de votre tête et entrez dans votre vie'),
       ('nl', 'The Software Craftsman: Professionalism, Pragmatism, Pride', 'De Software Craftsman: Professionaliteit, Pragmatisme, Trotsheid'),
       ('fr', 'The Software Craftsman: Professionalism, Pragmatism, Pride', 'L''artisan du logiciel : Professionnalisme, Pragmatisme, Fierté'),
       ('nl', 'Domain-Driven Design: Tackling Complexity in the Heart of Software', 'Domain-Driven Design: Complexiteit in het hart van de software aanpakken'),
       ('fr', 'Domain-Driven Design: Tackling Complexity in the Heart of Software', 'Domain-Driven Design: S''attaquer à la complexité au cœur du logiciel')
;

insert into translated_value (language, key, value)
values ('nl', 'Jeanne Boyarsky and Scott Selikoff', 'Jeanne Boyarsky en Scott Selikoff'),
       ('fr', 'Jeanne Boyarsky and Scott Selikoff', 'Jeanne Boyarsky et Scott Selikoff'),
       ('nl', 'Nathan Murray, Felipe Coury, Ari Lerner and Carlos Taborda', 'Nathan Murray, Felipe Coury, Ari Lerner en Carlos Taborda'),
       ('fr', 'Nathan Murray, Felipe Coury, Ari Lerner and Carlos Taborda', 'Nathan Murray, Felipe Coury, Ari Lerner et Carlos Taborda'),
       ('nl', 'Elisabeth Freeman and Kathy Sierra', 'Elisabeth Freeman en Kathy Sierra'),
       ('fr', 'Elisabeth Freeman and Kathy Sierra', 'Elisabeth Freeman et Kathy Sierra'),
       ('nl', 'Nicholas Locascio and Nikhil Buduma', 'Nicholas Locascio en Nikhil Buduma'),
       ('fr', 'Nicholas Locascio and Nikhil Buduma', 'Nicholas Locascio et Nikhil Buduma'),
       ('nl', 'Christopher A. Sims and Hillary Louise Johnson', 'Christopher A. Sims en Hillary Louise Johnson'),
       ('fr', 'Christopher A. Sims and Hillary Louise Johnson', 'Christopher A. Sims et Hillary Louise Johnson'),
       ('nl', 'Brad Green and Shyam Seshadri', 'Brad Green en Shyam Seshadri'),
       ('fr', 'Brad Green and Shyam Seshadri', 'Brad Green et Shyam Seshadri'),
       ('nl', 'Alexis Goldstein, Estelle Weyl and Louis Lazaris', 'Alexis Goldstein, Estelle Weyl en Louis Lazaris'),
       ('fr', 'Alexis Goldstein, Estelle Weyl and Louis Lazaris', 'Alexis Goldstein, Estelle Weyl et Louis Lazaris'),
       ('nl', 'Ted Husted and Vincent Massol', 'Ted Husted en Vincent Massol'),
       ('fr', 'Ted Husted and Vincent Massol', 'Ted Husted et Vincent Massol'),
       ('nl', 'Cornelis Bauer and Gavin King', 'Cornelis Bauer en Gavin King'),
       ('fr', 'Cornelis Bauer and Gavin King', 'Cornelis Bauer et Gavin King'),
       ('nl', 'Sander Mak and Paul Baker', 'Sander Mak en Paul Baker'),
       ('fr', 'Sander Mak and Paul Baker', 'Sander Mak et Paul Baker'),
       ('nl', 'Sandro Mancuso and Robert Cecil Martin', 'Sandro Mancuso en Robert Cecil Martin'),
       ('fr', 'Sandro Mancuso and Robert Cecil Martin', 'Sandro Mancuso et Robert Cecil Martin')
;
