INSERT INTO book (title, year_read) VALUES
    ('Oracle Certified Associate Java SE 8 Programmer I Study Guide', 2016),
    ('Ng-book: the complete book on Angular', 2019),
    ('Oracle Certified Professional Java SE 8 Programmer II Study Guide', 2019),
    ('The Clean Coder: A code of Conduct for Professional Programmers', 2018),
    ('Effective Java: A Programming Language Guide', 2019),
    ('Clean Code: A Handbook of Agile Software Craftsmanship', 2019),
    ('Head First design patterns', 2016),
    ('Fundamentals of Deep Learning', 2018),
    ('Succeeding with Agile: Software Development Using Scrum', 2017),
    ('The Elements of Scrum', 2016),
    ('7 Habits of highly effective people', 2018),
    ('How to win friends and influence people', 2018),
    ('AngularJS', 2017),
    ('HTML5 & CSS3 For The Real World', 2017),
    ('JUnit in Action', 2016),
    ('Mastering Unit Testing Using Mockito and JUnit', 2016),
    ('Spring in Action', 2017),
    ('Java Persistence with Hibernate', 2017);
